/**
 * Lookup for NetHack's 16×16 tile art (`src/render/tiles.json`, generated by
 * `scripts/gen-tiles.ts`; format documented in `docs/tiles.md`). Decodes the
 * compact pixel strings into `Tile` objects and caches them. Pure — the
 * Node-only `loadTiles` I/O lives in `src/tiles-load.ts` so `src/render/*`
 * stays browser-clean.
 */
import type { Tile } from '../model/types.js';
import tilesJson from './tiles.json' with { type: 'json' };

let loadedSet: TileSet | null = null;

/**
 * The bundled tile set (`tiles.json`, imported statically so this works in
 * Node and in the browser alike), parsed once and cached.
 */
export function loadTiles(): TileSet {
  if (loadedSet === null) loadedSet = tileSetFromFile(tilesJson as unknown as TileFile);
  return loadedSet;
}

/** Raw JSON shape of `tiles.json` (see docs/tiles.md). */
export interface TileFile {
  palette: Array<[number, number, number]>;
  monsters: Record<string, Record<string, string>>;
  objects: Record<string, string>;
  objectsByDescr: Record<string, string>;
  other: Record<string, string>;
}

/** Decoded tile set with a per-tile cache. */
export interface TileSet {
  readonly file: TileFile;
  readonly cache: Map<string, Tile>;
}

/** Base-64 alphabet matching `encodePixels` in `scripts/gen-tiles.ts`. */
const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
const B64IDX = new Map<string, number>([...B64].map((c, i) => [c, i]));

/** Build a `TileSet` around a decoded `TileFile` (used by `loadTiles` in the
 *  Node loader and by any browser-side loader that supplies the JSON itself). */
export function tileSetFromFile(file: TileFile): TileSet {
  return { file, cache: new Map() };
}

/** Decode one 256-char pixel string against the set palette. */
export function decodeTile(
  set: TileSet,
  key: string,
  pixels: string,
): Tile {
  const hit = set.cache.get(key);
  if (hit) return hit;
  if (pixels.length !== 256) {
    throw new Error(`tiles: tile "${key}" has ${pixels.length} pixels, expected 256`);
  }
  const out = new Uint8Array(256);
  for (let i = 0; i < 256; i++) {
    const v = B64IDX.get(pixels[i]!);
    if (v === undefined) throw new Error(`tiles: tile "${key}" has bad char at ${i}`);
    out[i] = v;
  }
  const tile: Tile = {
    w: 16,
    h: 16,
    pixels: out,
    palette: set.file.palette,
  };
  set.cache.set(key, tile);
  return tile;
}

/** Look up a monster tile by name (male by default, female when asked, falling back to the other). */
export function monsterTile(set: TileSet, name: string, female?: boolean): Tile | null {
  const entry = set.file.monsters[name.toLowerCase()];
  if (!entry) return null;
  const want = female === true ? 'f' : 'm';
  const pix = entry[want] ?? entry[want === 'm' ? 'f' : 'm'] ?? entry['n'];
  if (!pix) return null;
  return decodeTile(set, `mon:${name.toLowerCase()}:${want}`, pix);
}

/** Look up an object tile by name first, then by description. */
export function objectTile(set: TileSet, name?: string, descr?: string): Tile | null {
  if (name !== undefined) {
    const pix = set.file.objects[name.toLowerCase()];
    if (pix) return decodeTile(set, `obj:${name.toLowerCase()}`, pix);
  }
  if (descr !== undefined) {
    const pix = set.file.objectsByDescr[descr.toLowerCase()];
    if (pix) return decodeTile(set, `objdescr:${descr.toLowerCase()}`, pix);
  }
  return null;
}

/** Look up a dungeon-feature tile by name. */
export function otherTile(set: TileSet, name: string): Tile | null {
  const pix = set.file.other[name.toLowerCase()];
  if (!pix) return null;
  return decodeTile(set, `other:${name.toLowerCase()}`, pix);
}
